
from __future__ import annotations

_STYLE_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "fill": {"type": "string"},
        "stroke": {"type": "string"},
        "border_width": {"type": "integer", "minimum": 0},
        "border_color": {"type": "string"},
        "border_top_width": {"type": "integer", "minimum": 0},
        "border_top_color": {"type": "string"},
        "border_right_width": {"type": "integer", "minimum": 0},
        "border_right_color": {"type": "string"},
        "border_bottom_width": {"type": "integer", "minimum": 0},
        "border_bottom_color": {"type": "string"},
        "border_left_width": {"type": "integer", "minimum": 0},
        "border_left_color": {"type": "string"},
        "corner_radius": {"type": "integer", "minimum": 0},
        "corner_radius_top_left": {"type": "integer", "minimum": 0},
        "corner_radius_top_right": {"type": "integer", "minimum": 0},
        "corner_radius_bottom_left": {"type": "integer", "minimum": 0},
        "corner_radius_bottom_right": {"type": "integer", "minimum": 0},
        "padding_top": {"type": "integer", "minimum": 0},
        "padding_right": {"type": "integer", "minimum": 0},
        "padding_bottom": {"type": "integer", "minimum": 0},
        "padding_left": {"type": "integer", "minimum": 0},
        "padding_horizontal": {"type": "integer", "minimum": 0},
        "padding_vertical": {"type": "integer", "minimum": 0},
        "gap": {"type": "integer", "minimum": 0},
        "layout_direction": {"type": "string", "enum": ["horizontal", "vertical"]},
        "align_items": {"type": "string", "enum": ["start", "center", "end", "stretch", "baseline"]},
        "justify_content": {"type": "string", "enum": ["start", "center", "end", "space-between", "space-around", "space-evenly"]},
        "wrap": {"type": "string", "enum": ["no-wrap", "wrap"]},
        "width": {"oneOf": [{"type": "integer", "minimum": 0}, {"type": "string", "enum": ["fill", "hug"]}]},
        "height": {"oneOf": [{"type": "integer", "minimum": 0}, {"type": "string", "enum": ["fill", "hug"]}]},
        "min_width": {"type": "integer", "minimum": 0},
        "max_width": {"type": "integer", "minimum": 0},
        "min_height": {"type": "integer", "minimum": 0},
        "max_height": {"type": "integer", "minimum": 0},
        "flex_grow": {"type": "integer", "minimum": 0},
        "position": {"type": "string", "enum": ["auto", "absolute"]},
        "top": {"type": "integer"},
        "right": {"type": "integer"},
        "bottom": {"type": "integer"},
        "left": {"type": "integer"},
        "shadow": {"type": "string", "enum": ["none", "sm", "md", "lg", "xl", "2xl", "inner"]},
        "font_size": {"type": "integer", "minimum": 1},
        "font_family": {"type": "string"},
        "font_weight": {"type": "integer"},
        "line_height": {"type": "number"},
        "letter_spacing": {"type": "number"},
        "text_align": {"type": "string", "enum": ["left", "center", "right", "justify"]},
        "text_decoration": {"type": "string", "enum": ["none", "underline", "line-through"]},
        "text_transform": {"type": "string", "enum": ["none", "uppercase", "lowercase", "capitalize"]},
        "text_overflow": {"type": "string", "enum": ["visible", "clip", "ellipsis"]},
        "text_content": {"type": "string"},
        "max_lines": {"type": "integer", "minimum": 1},
        "opacity": {"type": "number", "minimum": 0, "maximum": 1},
        "overflow": {"type": "string", "enum": ["visible", "hidden", "scroll"]},
        "visible": {"type": "boolean"},
        "component_name": {"type": "string"},
        "icon_name": {"type": "string"},
        "image_placeholder": {"type": "string"},
        "svg_markup": {"type": "string"},
    },
    "additionalProperties": True,
}

FIGMA_NODE_SCHEMA: dict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["node_type", "name"],
    "properties": {
        "node_type": {
            "type": "string",
            "enum": [
                "frame", "auto_layout", "rectangle", "ellipse",
                "text", "line", "group", "component_instance",
            ],
        },
        "name": {"type": "string", "minLength": 1},
        "style": _STYLE_SCHEMA,
        "children": {
            "type": "array",
            "items": {"$ref": "#"},
        },
    },
    "additionalProperties": True,
}
